"""Writes REPORT.md from the stored outputs. Every number in the tables is read from a CSV."""
import numpy as np
import pandas as pd

from common import LINEAGE, OUT, ROOT
from report_tables import family_table, placebo_table, step1_table


def fmt(x, nd=3):
    if isinstance(x, (float, np.floating)) and not np.isfinite(x):
        return "inf" if x > 0 else "-"
    return f"{x:.{nd}f}"


def gate_table(g):
    ok = lambda b: "pass" if b else "**fail**"
    lines = ["| id | tier | rule (variant: config) | IS n / PF / expR | OOS n / PF / expR / $ | G1 OOS | G2 LOTO | G3 2x slip | G4 x0.95 / x1.05 | G5 OOS placebo mean / max | G6 DSR | G7 path | failed gates |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    fin = pd.read_csv(ROOT / "finalists.csv").set_index("finalist")
    for r in g.itertuples():
        lines.append(
            f"| {r.finalist} | {fin.loc[r.finalist, 'tier']} | {r.variant}: `{r.config}` | {int(r.IS_n)} / {fmt(r.IS_pf, 2)} / {fmt(r.IS_expR)} | "
            f"{int(r.OOS_n)} / {fmt(r.OOS_pf, 2)} / {fmt(r.OOS_expR)} / {r.OOS_usd:,.0f} | {ok(r.G1_oos)} | {r.LOTO_pos}/4 {ok(r.G2_loto)} | "
            f"{fmt(r.OOS_expR_slip2)} {ok(r.G3_slip2)} | {fmt(r.OOS_expR_x095)} / {fmt(r.OOS_expR_x105)} {ok(r.G4_mult)} | "
            f"{fmt(r.OOS_plc_mean)} / {fmt(r.OOS_plc_max)} {ok(r.G5_placebo)} | SR {fmt(r.IS_SR_trade)} {ok(r.G6_dsr)} | "
            f"{'needs 15m' if r.G7_needs_15m else 'ok'} | {r.failed} |")
    return "\n".join(lines)


def scope_table(fid):
    v = pd.read_csv(OUT / "validation_oos.csv")
    q = v[(v.finalist == fid) & (v.run == "base")]
    lines = ["| period | ticker | n | WR | PF | net expR | net $ | max DD $ |", "|---|---|---|---|---|---|---|---|"]
    for r in q.itertuples():
        lines.append(f"| {r.period} | {r.scope} | {int(r.n)} | {fmt(r.wr, 2)} | {fmt(r.pf, 2)} | {fmt(r.expR)} | {r.usd:,.0f} | {r.maxdd_usd:,.0f} |")
    return "\n".join(lines)


def year_md(fid):
    y = pd.read_csv(OUT / "finalist_year_tables.csv")
    y = y[(y.finalist == fid) & (y.ticker == "ALL")]
    lines = ["| year | period | n | WR | PF | net expR | net $ | max DD $ |", "|---|---|---|---|---|---|---|---|"]
    for r in y.itertuples():
        lines.append(f"| {int(r.year)} | {r.period} | {int(r.n)} | {fmt(r.wr, 2)} | {fmt(r.pf, 2)} | {fmt(r.expR)} | {r.usd:,.0f} | {r.maxdd_usd:,.0f} |")
    return "\n".join(lines)


def main():
    g = pd.read_csv(OUT / "validation_gates.csv")
    lo = pd.read_csv(OUT / "validation_loto.csv")
    dfl = pd.read_csv(OUT / "deflation.csv", header=None, index_col=0)[1]
    pw = pd.read_csv(OUT / "placebo_whole_search.csv").set_index("variant")
    real = pw.loc["REAL"]
    plc = pw.loc[[i for i in pw.index if "shift" in i]]
    canary = (OUT / "canary.txt").read_text()
    neff_txt = (OUT / "neff.txt").read_text().strip()
    cov = pd.read_csv(ROOT / "coverage_summary.csv")
    n_var = len(cov)
    f03, f05, f04 = (g.set_index("finalist").loc[k] for k in ("F03", "F05", "F04"))
    sb = pd.read_csv(OUT / "selection_bias_check.csv")
    sb_real = sb.share.iloc[0] * 100
    sb_plc_lo, sb_plc_hi = sb.share.iloc[1:].min() * 100, sb.share.iloc[1:].max() * 100
    fl = pd.read_csv(OUT / "deflation_floors.csv")
    pos = g[g.OOS_expR > 0]
    n_long = int(real.pass_long)
    md = f"""# REPORT - {LINEAGE}

Status tags: **[NEW]** = computed in this study; **[ARCHIVE]** = quoted from earlier work, not
re-verified; **[RECONSTRUCTION]** = this study's rebuild of an archive idea or of the native levels.
Every table below is generated by `src/build_report.py` from files in `outputs/`.

## 1. Verdict

**No strategy built on the weekly v42 / TrueALGO levels passed validation. [NEW]** Twelve rules were
frozen from 2013-2020 data and tested once on 2021-2026. None passed every gate. {len(pos)} of them kept a
small positive out-of-sample expectancy ({pos.OOS_expR.min():+.2f} to {pos.OOS_expR.max():+.2f} R per trade after costs) and
{len(g) - len(pos)} went negative. Every positive result sits inside the range the same rule produced on
placebo levels shifted 0.15-0.30 sigma.

The evidence points one way. On these four tickers the levels carry no information beyond their
distance from the weekly open:

* **Step 1 [NEW].** No level rejects price more often than arbitrary lines at nearby distances
  from WO. Pooled over tickers, 16 of 18 levels have a 95% interval on the excess that spans zero.
  The exceptions are *weaker* than their placebos: GB_BOT and RNG_B_HI at 0.25 sigma, RNG_T_LO and
  RNG_B_HI at 0.5 sigma. Arbitrary lines within 1.3 sigma of WO, where most touches happen, are
  rejected 36-55% of the time.
* **The whole search, run on placebo levels [NEW].** The identical 229,068-config grid run on
  levels shifted by -0.30 / -0.15 / +0.15 / +0.30 sigma gives
  {int(plc.screen_pass.iloc[0])} / {int(plc.screen_pass.iloc[1])} / {int(plc.screen_pass.iloc[2])} / {int(plc.screen_pass.iloc[3])}
  screen-passing configs. The real levels give {int(real.screen_pass)}. The real levels' top-10
  expectancy ({real.top10_mean_expR:.3f} R) is beaten by three of the four placebo sets.
* **What the in-sample winners really were.** {n_long} of the {int(real.screen_pass)} F0 passers are long trades:
  dip-buys at lower levels or breakouts through upper levels. Buying ES and NQ during 2013-2020
  paid +0.12 and +0.14 sigma per week on average (t = 2.7 and 3.7). That is drift in the market,
  not something the indicator found. Out of sample the finalists fell to {g.OOS_expR.min():+.2f} to
  {g.OOS_expR.max():+.2f} R per trade.

The answer to the mission question: **on this evidence, weeks of hand-extracting native levels
are not worth it.** The prompt states that v42 reproduces the native levels exactly on these
tickers, and this study's engine matches the v42 export to 1e-12 (Section 2). The native levels
would therefore behave the same way. Each level is a fixed percentage of WO; the static per-asset
vol and multipliers set the percentages. Any line at a similar distance does the same job.

## 2. Data, level engine, canary [NEW]

* Four TradingView 4h exports: ES, NQ, CL, 6J. Timestamps carry their own offset (UTC-9 / UTC-8,
  America/Anchorage). They are converted exactly, and bars start at 18, 22, 02, 06, 10, 14 ET.
* A week runs from Sunday 18:00 ET; WO is the open of its first 4h bar. Weeks run 2013-01-28
  (6J 2016-10-17) to 2026-09-21. In-sample (IS) is up to 2020-12-28: 414 weeks each for ES / NQ /
  CL and 220 for 6J. Out-of-sample (OOS) is 299 weeks per ticker. The final week is incomplete:
  its 3 trades are marked at the latest close.
* Levels come from the pine WEEKLY engine: static vol / bias / SD multipliers, with GP and range
  boxes. ATR(14) is Wilder's, taken on CME trading-day bars as of the last day before the week.
* Canary:

```
{canary.strip()}
```

* The four levels NQ, CL and 6J use are computed from the pine math; those exports had no level
  columns to check against. ES matches the export on all 18 level columns in 717 weeks.

## 3. Execution model [NEW]

* Micros: MES, MNQ, MCL, MJY. $4.50 commission per contract round turn. One tick of slippage
  on every entry, stop exit and time exit; limit targets get none.
* Size is 0.5% of a $100,000 account ($500) divided by the *planned* stop distance, rounded down.
  The trade is skipped if one micro exceeds $500. Out of sample this skips many NQ trades with
  1-ATR stops, because one MNQ then risks more than $500.
* A limit fills only if price trades one tick through. When stop and target fall in the same 4h
  bar, the stop fills. A target inside the fill bar of a resting limit counts only if the bar
  closes beyond it. A stop gapped through fills at the open. Everything is flat at the close of
  the week's last 4h bar, with one position per ticker.
* A bug was found and fixed before any validation. The first kernel sized trades on the actual
  fill. A resting limit that filled on a gap next to its stop then got a one-point risk, which
  created 400R trades. Sizing now uses the order price (or the signal bar's close for next-open
  entries), which is what a trader knows when sending a bracket order. F0 and every round were
  re-run. The pre-fix round-1 summary is kept at `outputs/prefix_sizing_bug_round1_summary.csv`,
  and the pre-fix configs are counted in N.

## 4. Step 1 - level strength map, excess over placebo (IS, pooled) [NEW]

A first touch is the first 4h bar that trades through the level. P(rej X) is the chance that
price comes back X sigma toward WO before extending X sigma further. Ambiguous bars count against
the level. The placebo is the mean of the same measure for lines at the level's distance +-0.15
and +-0.30 sigma; placebos that would cross WO are dropped. The 95% intervals come from a 2,000x
paired week bootstrap. Per-ticker rows are in `outputs/step1_level_strength.csv`, and the null
curve (P(reject) against distance for arbitrary lines) is in `outputs/step1_null_curve.csv`.

{step1_table()}

Ranked by excess over placebo, no level stands out. The largest positive excess (RNG_T_HI, +0.05
at 0.25 sigma) has an interval touching zero. With 36 pooled tests, about two intervals would
clear zero by chance. Four do, and all four are negative: those levels are rejected *less* often
than nearby arbitrary lines.

## 5. Step 2 / 2B - strategy search [NEW]

**F0 pierce grid.** 18 levels x {{bounce, breakout}} x {{ATR, sigma}} units x 7 pierce depths x 5
entry styles (resting limit / stop, reclaim, reclaim within 1 / 2 / 3 bars) x max pierce
{{0.5, 1.0, 1.5}} x 7 stops x 8 targets. That is 4,248 entry cells and 229,068 configs, each run
on 4 tickers plus a pooled scope, all in-sample. Full rows are in `results_all_F0.csv.gz`. PF and
expectancy heatmaps for every level / side / unit are in `outputs/heatmaps/`. The screen
(`src/screen.py`) requires n >= 100 pooled, PF >= 1.3, positive net expectancy, breadth across
tickers, and the plateau rule: every +-1-step neighbour positive with median neighbour PF >= 1.3.

**Whole-search placebo and robustness grids.**

{placebo_table()}

**EXPAND rounds.** There were {n_var - 1} filter variants in 3 rounds. Each is the full F0 grid
under a filter, run on the real levels and on the 4 placebo shifts. A family passes only if its
real-level search beats at least 3 of its 4 placebo searches on both the number of screen passers
and top-10 expectancy. That test is weak: under the null, a real search lands in the top two of
five on one metric 40% of the time, and requiring both metrics lowers that only somewhat.

{family_table()}

Round 1 produced one pass, DOW_WedThu (entries only on Wednesday / Thursday trading dates), and it
was narrow. Its refinement in round 3 (Wed only, Thu only, Tue-Thu) failed, and rounds 2 and 3
produced no pass, which meets the stop rule. Coverage: {n_var} variants x 16,992 ticker-cells, all
done, 0 errors, 0 pending (`coverage.csv.gz`, `coverage_summary.csv`). The families and their
statuses are in `ideas_queue.md`.

## 6. Overfitting guard [NEW]

* N (honest): {int(dfl['n_unique']):,} unique real-level configs evaluated. Adding the pre-fix
  sizing run gives {int(dfl['n_all']):,}.
* Effective N: {neff_txt}. Entry sets overlapping by more than 0.7 (Jaccard) share a cluster, and
  all stop / target variants of one entry rule share an entry set.
* Deflated Sharpe floor, per trade, from the cross-trial variance (the pre-set estimator):
  SR0 = {dfl['sr0_all']:.2f} (N_all), {dfl['sr0_eff']:.2f} (N_eff). This variance is inflated by tiny-stop configs
  whose costs make them lose almost every trade. More lenient floors do not change any verdict:
  robust (MAD) variance gives {fl.sr0_Nall.iloc[1]:.2f} / {fl.sr0_Neff.iloc[1]:.2f}, and the null variance 1/T gives
  {fl.sr0_Nall.iloc[2]:.2f} / {fl.sr0_Neff.iloc[2]:.2f}. The finalists' in-sample per-trade Sharpe is
  {g.IS_SR_trade.min():.2f}-{g.IS_SR_trade.max():.2f}. Every finalist that would clear the most lenient floor fails another gate.

## 7. Step 4 - frozen finalists, validation (2021+ opened once) [NEW]

Finalists were frozen in commit `609ac2a` (`FREEZE.md`, `finalists.csv`) before any 2021+ data was
read. `OOS_UNSEALED` records the single opening. There were three tiers: **A** = the six best entry
clusters from F0 and from the one family that passed the screen (DOW_WedThu), **B** = the archive
leads, **C** = the four best remaining clusters from the whole pool, as a check on generic effects. The gates are listed
in `src/validate.py`. G5 compares the rule's OOS expectancy with the same rule on the four placebo
level sets. OOS is the only place that comparison is unbiased, because in-sample selection alone makes a config beat its own placebo:
{sb_real:.0f}% of real-level passers do, and {sb_plc_lo:.0f}-{sb_plc_hi:.0f}% of placebo-level passers beat their real-level
twin (`outputs/selection_bias_check.csv`).

{gate_table(g)}

LOTO detail is in `outputs/validation_loto.csv`. For each held-out ticker, the rule is re-selected
from the same level / side / unit on the other three tickers, then scored on the held-out ticker
in-sample.

![finalists](outputs/finalists_is_vs_oos.png)

## 8. Closest failures

None of these are EV+ by the prompt's standard, so the Step 5 rulebook / trade-list / year-table
deliverables apply to no strategy. They are given here for the closest failures, so it is clear
how close they came and why they fail. The frozen trade lists of all 12 finalists (IS and OOS)
are in `outputs/finalist_trades_all.csv`.

**F03** ({f03.variant}: `{f03.config}`) failed G2 (LOTO {int(f03.LOTO_pos)}/4) and G6 (DSR). It passed G1 at
exactly PF {f03.OOS_pf:.2f} with {int(f03.OOS_n)} OOS trades and {f03.OOS_expR:+.3f} R, and it passed G3, G4 and G5 against the placebo
mean. It passes G3 and G4 only in the weak sense (expectancy stays positive): with 2x slippage and
with the multipliers at x0.95 / x1.05 its PF drops below 1.20 (see `outputs/validation_oos.csv`).
Its OOS expectancy ({f03.OOS_expR:.3f}) is below the same rule on levels shifted 0.15 sigma outward
({f03.OOS_plc_max:.3f}), so the level adds nothing a nearby line would not. Rule as frozen: each week, on Wednesday and Thursday
CME trading dates only (Tuesday 18:00 ET to Thursday 17:00 ET), rest a buy limit at
WRL - 0.50 sigma. The stop is 0.50 sigma below the limit and the target 0.50 sigma above it,
which puts the target back at WRL itself. Take
one trade per ticker-week and exit at the week's last 4h close if neither is hit. sigma = WO x vol /
sqrt(52), and WRL = WO - sigma x 2(1 - bias) x wrl_mult, using the pine per-asset constants.

{scope_table('F03')}

{year_md('F03')}

**F05** ({f05.variant}: `{f05.config}`) failed G1 (OOS PF {f05.OOS_pf:.2f} < 1.20) and G6. It passed LOTO
({int(f05.LOTO_pos)}/4), 2x slippage, x0.95 / x1.05 and the placebo mean ({f05.OOS_expR:.3f} vs {f05.OOS_plc_mean:.3f}), but a placebo
set reached {f05.OOS_plc_max:.3f}. Rule: in a week where the first 4h close above RNG_T_LO (WRH - 0.078
sigma) falls so that the next bar is on a Wednesday / Thursday trading date, buy that bar's open.
The stop is 1.0 ATR(14) below RNG_T_LO and the target 0.5 ATR above the entry.

{scope_table('F05')}

**F04** ({f04.variant}: `{f04.config}`) failed G1 ({int(f04.OOS_n)} OOS trades < 100, PF {f04.OOS_pf:.2f}) and G6. It needs 15m
path resolution (pierce 0.10 ATR). OOS {f04.OOS_expR:+.3f} R against a placebo max of {f04.OOS_plc_max:.3f}.

The three archive leads, reconstructed [RECONSTRUCTION], all failed:
* WTL1 bounce, archive 57.7% WR / PF 1.80 [ARCHIVE]. As F07 it scored IS PF {g.set_index('finalist').loc['F07', 'IS_pf']:.2f}
  and OOS PF {g.set_index('finalist').loc['F07', 'OOS_pf']:.2f} / {g.set_index('finalist').loc['F07', 'OOS_expR']:+.3f} R.
* WRL bounce, archive 69.4% WR / PF 1.44 over 312 weeks [ARCHIVE]. As F02 it scored IS PF
  {g.set_index('finalist').loc['F02', 'IS_pf']:.2f} and OOS PF {g.set_index('finalist').loc['F02', 'OOS_pf']:.2f} / {g.set_index('finalist').loc['F02', 'OOS_expR']:+.3f} R.
* W RB Top long with momentum filter DM < 0.40, archive 67 SPY trades, PF 1.54 [ARCHIVE]. "DM" is
  undefined in the archive; it was rebuilt as |prior-week move| < 0.40 sigma. No version reaches
  100 in-sample trades. As F08 it scored OOS PF {g.set_index('finalist').loc['F08', 'OOS_pf']:.2f} on {int(g.set_index('finalist').loc['F08', 'OOS_n'])} trades, too few for G1, with LOTO 0/4.

## 9. Limits of this study

* Path resolution (G7) was not run on 15m data. The TradingView connector's 15m history starts
  2026-07-13, about 10 weeks. No finalist reached the stage where it would decide the verdict. The
  4h fill model is pessimistic (stop-first, fill-bar targets only on a close), so 15m data would
  more likely raise results than lower them. It would still be required before trading any rule
  with a pierce or stop under 0.3 ATR.
* Only four tickers, and all four were used for design; there was no held-out ticker. LOTO is the
  ticker split. 6J has 4.2 in-sample years.
* The continuous contracts are unadjusted. Mid-week roll gaps shift levels relative to price in
  roughly 2-7% of in-sample weeks, depending on the ticker (flagged in `data.py`), exactly as they
  do on the native chart.
* The DM filter and the "momentum filter" of the archive could not be reproduced exactly (see above).
* The daily Hybrid layer (EWMA vol) and the monthly layer were not searched as trading levels;
  the prompt limits the mission to the weekly engine. The monthly levels appear only as a
  confluence filter, and it failed.

## 10. Files

| file | what |
|---|---|
| `FREEZE.md`, `finalists.csv`, `OOS_UNSEALED` | frozen rules, hash, single OOS opening |
| `search_manifest.md`, `ideas_queue.md`, `coverage.csv.gz`, `coverage_summary.csv` | search space, families, coverage |
| `results_all_F0.csv.gz`, `results_expand_round*.csv.gz` | IS metrics, config x ticker |
| `outputs/step1_*.csv` | level strength map, null curve |
| `outputs/placebo_whole_search.csv`, `outputs/families/round*_summary.csv` | whole-search placebo controls |
| `outputs/validation_*.csv`, `outputs/deflation.csv`, `outputs/neff*.{{txt,csv}}` | gates, LOTO, OOS runs, deflation |
| `outputs/finalist_trades_all.csv`, `outputs/finalist_year_tables.csv` | frozen trade lists (IS + OOS), per ticker / year |
| `outputs/heatmaps/` | PF and expectancy heatmaps, F0 |
| `run_all.sh`, `src/`, `tests/` | reproduce everything in-sample (about 1 h on 4 cores) |
"""
    (ROOT / "REPORT.md").write_text(md)
    print(md[:3000])


if __name__ == "__main__":
    main()
